sudo: true
dist: trusty
language: node_js
node_js:
    - "10"

cache: npm

before_install:
    - npm i -g npm@latest

install:
    - npm install

jobs:
    include:
        - stage: test
          script: scripts/test
        - stage: test
          script: scripts/build
