sudo: false
dist: trusty
language: node_js

cache: npm

before_install:
    - npm i -g npm@latest

install:
    - npm install

jobs:
    include:
        - stage: test
          script: script/test
        - stage: test
          script: script/build
